version: '3'
services:
  server:
    build: .
    env_file:
      - ./envs/${ENV}.env
    container_name: geptyro-bot-${ENV}
    volumes:
      - ./:/app:cached
      - /app/node_modules
    working_dir: /app